# Tensor exercises

Just to make sure that the basics stick, we are going to have some small exercises for what we went through.

In [1]:
import torch

## Basics: initialization, shape, type and device

Here are a few practice runs for initializing tensors. If there is something new or you cannot remember how to do something (which happens to us all the time), have a look into the More creation options can be found [docs](https://pytorch.org/docs/stable/torch.html#creation-ops).

#### E1

In [ ]:
# create tensor with shape (3,3) and all values 0
# check its type and make sure it is integer

#### E2

In [ ]:
# create a tensor of shape (2,4) with all values 1
# make sure the values are floats

#### E3

In [9]:
# can you transform the following boolean tensor to a float tensor and back to a boolean tensor?

#### E4

In [14]:
# what happens to the following tensor as boolean?

t = torch.tensor([[1,0,2],[0,0.5,0]])
print(t)

# we know that 0 is False and 1 is True, but what if there are other values?

tensor([[1.0000, 0.0000, 2.0000],
        [0.0000, 0.5000, 0.0000]])


#### E5

In [16]:
# here is a dataframe

import pandas as pd
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})

# convert its values to a tensor

## Tensor operations

### Indexing, slicing and concatenating

#### E1

In [18]:
# change the first row of the following tensor to 0

t = torch.ones(3,3) * 2
print(t)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


#### E2

In [20]:
# change the first column of the following tensor to 0

t = torch.ones(3,3) * 2
print(t)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


#### E3

In [39]:
# find all the values in the following tensor that are greater than 1
# and replace them with 1

t = torch.tensor([[1,0,2],[0,0.5,0],[3,1,0]])
print(t)

tensor([[1.0000, 0.0000, 2.0000],
        [0.0000, 0.5000, 0.0000],
        [3.0000, 1.0000, 0.0000]])


#### E4

In [45]:
# select the first two rows and the last two columns of the following tensor

t = torch.tensor([[1,0,2,0],[0,0.5,0,2],[3,1,0,0.5]])
print(t)

tensor([[1.0000, 0.0000, 2.0000, 0.0000],
        [0.0000, 0.5000, 0.0000, 2.0000],
        [3.0000, 1.0000, 0.0000, 0.5000]])


#### E5

In [43]:
# concatenate the following tensors in the second dimension

t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])

### Element-wise operations

#### E1: Create two tensors of the same shape and add them together

#### E2: Create a tensor of shape (2,3) and multiply each element by 2

#### E3: Multiply all elements of a (2,3)-shape tensor with another tensor of shape (2,3)

#### E4: For a given tensor, perform log normalization after adding 1 to each element

In [57]:
t = torch.tensor([[1,2,0],[0,5,0]])

### Reduction operations

#### E1: create a tensor of shape (4,5) with random values and take its mean over the first dimension

#### E2: Create a random tensor with shape (4,5) and take the sum over dimension two

### Matrix operations

#### E1: Multiply a tensor of shape (2,3) with its transpose (matrix multiplication)

Tip: tensor.t() or tensor.T gives you the transposed form of a tensor

## Broadcasting and tensor modification

#### E1: Here are two random tensors of shape (3,4) and (3,). Modify one of their shapes in such a way that you can add the second tensor to the first.

In [63]:
t1 = torch.randn(3,4)
t2 = torch.randn(3)

t1 + t2

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

#### E2: Find a way to add the elements of the following two tensors in order

In [65]:
t1 = torch.randn(6)
t2 = torch.randn(2,3)