# Tensor exercises

Just to make sure that the basics stick, we are going to have some small exercises for what we went through.

In [1]:
import torch

## Basics: initialization, shape, type and device

Here are a few practice runs for initializing tensors. If there is something new or you cannot remember how to do something (which happens to us all the time), have a look into the More creation options can be found [docs](https://pytorch.org/docs/stable/torch.html#creation-ops).

#### E1

In [ ]:
# create tensor with shape (3,3) and all values 0
# check its type and make sure it is integer

#### S1

In [5]:
# solution

# option 1
t = torch.zeros(3,3)
print(t)
print(t.dtype)
t = t.type(torch.int)
print(t.dtype)

# option 2
t = torch.Tensor(3,3).fill_(0)
print(t)
print(t.dtype)
t = t.type(torch.int)
print(t.dtype)

# option 3
t = torch.tensor([[0,0,0],[0,0,0],[0,0,0]])
print(t)
print(t.dtype)
t = t.type(torch.int)
print(t.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.int32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.int32
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64
torch.int32


#### E2

In [ ]:
# create a tensor of shape (2,4) with all values 1
# make sure the values are floats

#### S2

In [6]:
# solution

# option 1
t = torch.ones(2,4)
print(t)
print(t.dtype)
t = t.type(torch.float)
print(t.dtype)

# option 2
t = torch.Tensor(2,4).fill_(1)
print(t)
print(t.dtype)
t = t.type(torch.float)
print(t.dtype)

# option 3
t = torch.tensor([[1,1,1,1],[1,1,1,1]])
print(t)
print(t.dtype)
t = t.type(torch.float)
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.float32
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.int64
torch.float32


#### E3

In [9]:
# can you transform the following boolean tensor to a float tensor and back to a boolean tensor?

t = torch.tensor([[True, False, True],[False, True, False]])
print(t)

#### S3

In [10]:
# solution

# transform to float
t = t.type(torch.float)
print(t)
# transform back to boolean
t = t.type(torch.bool)
print(t)

tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[1., 0., 1.],
        [0., 1., 0.]])
tensor([[ True, False,  True],
        [False,  True, False]])


#### E4

In [14]:
# what happens to the following tensor as boolean?

t = torch.tensor([[1,0,2],[0,0.5,0]])
print(t)

# we know that 0 is False and 1 is True, but what if there are other values?

tensor([[1.0000, 0.0000, 2.0000],
        [0.0000, 0.5000, 0.0000]])


#### S4

In [15]:
# solution

t = t.type(torch.bool)
print(t)
# anything non-zero is True

tensor([[ True, False,  True],
        [False,  True, False]])


#### E5

In [16]:
# here is a dataframe

import pandas as pd
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})

# convert its values to a tensor

#### S5

In [17]:
# solution

t = torch.tensor(df.values)
print(t)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


## Tensor operations

### Indexing, slicing and concatenating

#### E1

In [18]:
# change the first row of the following tensor to 0

t = torch.ones(3,3) * 2
print(t)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


#### S1

In [19]:
# solution

t[0] = 0
print(t)

tensor([[0., 0., 0.],
        [2., 2., 2.],
        [2., 2., 2.]])


#### E2

In [20]:
# change the first column of the following tensor to 0

t = torch.ones(3,3) * 2
print(t)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


#### S2

In [21]:
# solution

t[:,0] = 0
print(t)

tensor([[0., 2., 2.],
        [0., 2., 2.],
        [0., 2., 2.]])


#### E3

In [39]:
# find all the values in the following tensor that are greater than 1
# and replace them with 1

t = torch.tensor([[1,0,2],[0,0.5,0],[3,1,0]])
print(t)

tensor([[1.0000, 0.0000, 2.0000],
        [0.0000, 0.5000, 0.0000],
        [3.0000, 1.0000, 0.0000]])


#### S3

In [42]:
# solution

option = 1

# choose case defined by option and execute that (use case switch)
match option:
    case 1:
        # as in course
        mask = t>1
        t[mask] = 1
    case 2:
        # option 2
        t[t>1] = 1
    case 3:
        # option 3
        t = torch.where(t>1,torch.tensor(1),t)
    case 4:
        # option 4
        t = torch.clamp(t,0,1)
    case _:
        print('invalid option')

print(t)

# as in course (option 1)
#mask = t>1
#t[mask] = 1
#print(t)

# option 2
#t[t>1] = 1
#print(t)

# option 3
#t = torch.where(t>1,torch.tensor(1),t)
#print(t)

# option 4
#t = torch.clamp(t,0,1)
#print(t)

tensor([[1.0000, 0.0000, 1.0000],
        [0.0000, 0.5000, 0.0000],
        [1.0000, 1.0000, 0.0000]])


#### E4

In [45]:
# select the first two rows and the last two columns of the following tensor

t = torch.tensor([[1,0,2,0],[0,0.5,0,2],[3,1,0,0.5]])
print(t)

tensor([[1.0000, 0.0000, 2.0000, 0.0000],
        [0.0000, 0.5000, 0.0000, 2.0000],
        [3.0000, 1.0000, 0.0000, 0.5000]])


#### S4

In [46]:
# solution

t = t[:2,-2:]
print(t)

tensor([[2., 0.],
        [0., 2.]])


#### E5

In [43]:
# concatenate the following tensors in the second dimension

t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])

#### S5

In [44]:
# solution

t = torch.cat((t1,t2),dim=1)
print(t)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


### Element-wise operations

#### E1: Create two tensors of the same shape and add them together

#### S1

In [49]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])

# option 1
t = torch.add(t1,t2)
print(t)

# ooption 2
t = t1 + t2
print(t)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])


#### E2: Create a tensor of shape (2,3) and multiply each element by 2

#### S2

In [48]:
t = torch.tensor([[1,2,3],[4,5,6]])
t = t * 2
print(t)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


#### E3: Multiply all elements of a (2,3)-shape tensor with another tensor of shape (2,3)

#### S3

In [56]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])

# option 1
t = torch.mul(t1,t2)
print(t)

# option 2
t = t1 * t2
print(t)

tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])


#### E4: For a given tensor, perform log normalization after adding 1 to each element

In [57]:
t = torch.tensor([[1,2,0],[0,5,0]])

#### S4

In [58]:
# add 1 to all the values in the following tensor
t += 1
print(t)

# take the log of t
t = torch.log(t)
print(t)

tensor([[2, 3, 1],
        [1, 6, 1]])
tensor([[0.6931, 1.0986, 0.0000],
        [0.0000, 1.7918, 0.0000]])


### Reduction operations

#### E1: create a tensor of shape (4,5) with random values and take its mean over the first dimension

#### S1

In [61]:
# create random tensor of shape (4,5)
# and find the mean of each row
t = torch.randn(4,5)
print(t)
means = t.mean(dim=0)
print(means)

tensor([[-0.1413, -1.6261,  0.9676, -1.6082,  0.8467],
        [-1.1308,  0.6192, -0.3533, -1.2482, -1.1031],
        [-0.3127, -0.6377,  0.0903,  0.6774,  0.1267],
        [-0.8729, -1.1228, -1.0584,  2.5954, -0.8856]])
tensor([-0.6144, -0.6918, -0.0885,  0.1041, -0.2538])


#### E2: Create a random tensor with shape (4,5) and take the sum over dimension two

#### S2

In [62]:
# create random tensor of shape (4,5)
t = torch.randn(4,5)
print(t)

# sum over the second dimension
sums = t.sum(dim=1)
print(sums)

tensor([[-0.4760, -0.0276,  0.1640, -0.4997, -0.0356],
        [ 2.1732, -0.2810,  1.6851, -0.7698,  0.8736],
        [-1.4498, -0.7604,  0.8082,  0.3751,  0.0810],
        [ 0.0614,  1.0113,  0.9018, -0.7359,  0.0742]])
tensor([-0.8748,  3.6810, -0.9460,  1.3127])


### Matrix operations

#### E1: Multiply a tensor of shape (2,3) with its transpose (matrix multiplication)

Tip: tensor.t() or tensor.T gives you the transposed form of a tensor

#### S1

In [54]:
t1 = torch.tensor([[1,2,3],[4,5,6]])

# option 1
t = torch.matmul(t1,t1.T)
print(t)

# option 2
t = t1 @ t1.T
print(t)

# option 3
t = t1.mm(t1.T)
print(t)

# option 4
t = torch.mm(t1,t1.T)
print(t)

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])


## Broadcasting and tensor modification

#### E1: Here are two random tensors of shape (3,4) and (3,). Modify one of their shapes in such a way that you can add the second tensor to the first.

In [63]:
t1 = torch.randn(3,4)
t2 = torch.randn(3)

t1 + t2

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

#### S1

In [64]:
t1 + t2.unsqueeze(1)

tensor([[-0.5579, -1.0514,  2.2625,  0.5759],
        [ 0.4819, -0.3863,  0.5028, -0.5366],
        [-0.1636, -0.1922, -1.7194, -0.2959]])

#### E2: Find a way to add the elements of the following two tensors in order

In [65]:
t1 = torch.randn(6)
t2 = torch.randn(2,3)

#### S2

In [66]:
t1.view(2,3) + t2

tensor([[ 0.5174, -1.7048, -1.2065],
        [ 1.7657, -2.4456, -0.7037]])