I lost the source, but some blog post.

Importing pytorch

In [ ]:
import torch

Ways of instantiating tensors

In [ ]:
zeroes = torch.zeros(4, 16)
print(zeroes)
print(zeroes.size())

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([4, 16])


In [ ]:
ones = torch.ones(4, 16)
print(ones)
print(ones.size())

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([4, 16])


In [ ]:
t1 = torch.randn(4, 16)
print(t1)
print(t1.size())

tensor([[-1.6625e+00,  2.7177e+00,  4.9130e-01,  1.8090e+00, -1.3411e+00,
         -4.5905e-01,  4.7142e-01, -9.5383e-01, -2.9791e-01, -5.2851e-01,
          6.6089e-02,  8.5424e-01, -1.1891e+00, -1.1895e+00,  6.2220e-01,
          4.0285e-01],
        [-2.5563e-01,  1.8037e-01, -1.5442e+00,  1.8908e-01,  3.9931e-01,
         -7.0743e-02, -1.2112e+00, -4.1002e-01, -1.5551e+00,  1.0182e-01,
         -1.4707e+00, -5.3761e-01,  1.0555e+00,  2.1762e+00,  9.3005e-01,
          7.3458e-01],
        [-1.1812e-01, -1.5754e+00,  4.6611e-02,  4.1436e-01, -1.3442e+00,
          1.9156e+00,  1.9344e+00,  2.4035e-01, -1.1219e+00,  1.0170e+00,
          1.5101e+00,  1.1113e+00,  4.2972e-01, -5.3302e-01,  1.0092e+00,
         -1.2324e+00],
        [ 1.5304e-01,  2.2364e-02, -5.1401e-01,  1.3421e+00, -1.3519e+00,
          5.6560e-01, -1.7277e+00, -2.0341e+00,  1.8083e-01,  1.4258e+00,
          2.1304e+00,  6.8268e-02,  1.5944e+00,  7.8090e-01,  7.3802e-04,
         -9.4927e-01]])
torch.Size([4, 16])

In [ ]:
a_list = [1, 2, 3, 4]
t2 = torch.tensor(a_list)
print(t2)
print(t2.size())

tensor([1, 2, 3, 4])
torch.Size([4])


In [ ]:
nested_list = [[-1, 2, -3, 4], [-5, 6, -7, 8]]
t2 = torch.tensor(nested_list, dtype=torch.float)
print(t2)
print(t2.size())

tensor([[-1.,  2., -3.,  4.],
        [-5.,  6., -7.,  8.]])
torch.Size([2, 4])


Move a tensor to the GPU

In [ ]:
if torch.cuda.is_available:
  t2 = t2.to('cuda')
print(t2)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], device='cuda:0')


Move a tensor from GPU to CPU

In [ ]:
t2 = t2.to('cpu')
print(t2)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


Type casting

In [ ]:
t2 = t2.int()
print(t2)

tensor([[-1,  2, -3,  4],
        [-5,  6, -7,  8]], dtype=torch.int32)


Use built in math operators to transform in parallel (never use loops to iterate over elements of a tensor)

In [ ]:
t2 = t2.abs()
print(t2)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)


The first dimension is usually the batch dimension. That means that each element of dimension 0 is an input or output of an independent instance in a neural net. Try to make sure any transformations are only done on dimensions other than 0.

In [ ]:
t3 = torch.sum(t2, dim=1)
print(t3)
print(t3.size())

tensor([10, 26])
torch.Size([2])


Something more complicated. Imagine you have a 4x4 screen of pixels from an RGB screen. That is, each value is R, G, or B values in the range [0, 255]. You might have the R, G, and B channels separated out so that all the red channel values for each pixel are in dimension 0, all the green channel values for each pixel are in dimension 1, and all the blue channel values for each pixel are in dimension 2.

In [ ]:
threedee_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],
                 [[17, 18, 19, 20], [21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]],
                 [[33, 34, 35, 36], [37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]]
t4 = torch.tensor(threedee_list)
print(t4)
print(t4.size())

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])
torch.Size([3, 4, 4])


Pixel 0,0 would have the RGB value of...

In [ ]:
pixel = [t4[0][0][0], t4[1][0][0], t4[2][0][0]]
print(pixel)

[tensor(1), tensor(17), tensor(33)]


If you have a single element in a tensor and you want the value out of the tensor so you can do normal python stuff with it use ```.item()```

In [ ]:
pixel = [t4[0][0][0].item(), t4[1][0][0].item(), t4[2][0][0].item()]
print(pixel)

[1, 17, 33]


But you can slice tensors along each dimension. For example to get all values at 0x0...



In [ ]:
pixel_tensor = t4[:, 0, 0]
print(pixel_tensor)

tensor([ 1, 17, 33])


You can get regular python lists out of tensors too

In [ ]:
pixel_list = pixel_tensor.tolist()
print(pixel_list)

[1, 17, 33]


Math with tensors and scalars

In [ ]:
t4.float() / 2

tensor([[[ 0.5000,  1.0000,  1.5000,  2.0000],
         [ 2.5000,  3.0000,  3.5000,  4.0000],
         [ 4.5000,  5.0000,  5.5000,  6.0000],
         [ 6.5000,  7.0000,  7.5000,  8.0000]],

        [[ 8.5000,  9.0000,  9.5000, 10.0000],
         [10.5000, 11.0000, 11.5000, 12.0000],
         [12.5000, 13.0000, 13.5000, 14.0000],
         [14.5000, 15.0000, 15.5000, 16.0000]],

        [[16.5000, 17.0000, 17.5000, 18.0000],
         [18.5000, 19.0000, 19.5000, 20.0000],
         [20.5000, 21.0000, 21.5000, 22.0000],
         [22.5000, 23.0000, 23.5000, 24.0000]]])

What if I wanted all the pixels in each channel in a single row instead of a matrix? ```.view()``` changes the shape without changing the underlying structure of the data.

In [ ]:
num_pixels = t4.size()[1]*t4.size()[2]
num_channels = t4.size()[0]
t4.view(num_channels, num_pixels)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

Suppose you had two 4x4 RGB screens

In [ ]:
t5 = torch.randn(2, 3, 4, 4)
print(t5)
print(t5.size())

tensor([[[[-0.4680, -0.1794,  1.5356, -1.1662],
          [ 0.3892, -0.3884, -1.9835,  0.9022],
          [ 0.3620, -0.4374,  0.0507, -0.2595],
          [-0.3166,  0.0512,  0.8866,  2.1632]],

         [[-0.0888, -1.2013,  1.2385,  2.8678],
          [-0.1893, -1.9294,  0.6458, -1.2946],
          [-0.5045,  0.2533, -1.0932, -0.7044],
          [ 1.0345,  0.5941, -0.3620, -0.8867]],

         [[ 1.9300,  1.3803,  1.8367, -0.1224],
          [-0.5968,  0.7930,  0.7457,  0.8375],
          [ 1.2043, -0.1018,  0.5469, -1.7117],
          [ 0.2851, -0.3779, -2.5378, -0.6425]]],


        [[[ 0.7711, -0.1986, -0.2374,  2.5042],
          [ 1.2424, -1.1035, -0.2942,  0.4099],
          [-1.0478,  0.8026,  0.4255, -0.0128],
          [ 0.5143,  0.2421, -0.2203,  1.2130]],

         [[ 0.5058, -1.1765,  0.1627, -0.0310],
          [-0.7204, -1.8918,  0.3841, -0.0335],
          [-0.2934,  1.1392,  0.9415,  0.3601],
          [ 0.6677, -0.2036,  0.0291,  0.2366]],

         [[ 0.2782,  0.5943,

Wait, I can't have negative RGB values. I want to know which elements are negative.

In [ ]:
mask = t5 < 0.0
print(mask)

tensor([[[[ True,  True, False,  True],
          [False,  True,  True, False],
          [False,  True, False,  True],
          [ True, False, False, False]],

         [[ True,  True, False, False],
          [ True,  True, False,  True],
          [ True, False,  True,  True],
          [False, False,  True,  True]],

         [[False, False, False,  True],
          [ True, False, False, False],
          [False,  True, False,  True],
          [False,  True,  True,  True]]],


        [[[False,  True,  True, False],
          [False,  True,  True, False],
          [ True, False, False,  True],
          [False, False,  True, False]],

         [[False,  True, False,  True],
          [ True,  True, False,  True],
          [ True, False, False, False],
          [False,  True, False, False]],

         [[False, False,  True, False],
          [False,  True, False, False],
          [ True,  True, False, False],
          [False, False,  True, False]]]])


Make all the negative values into zero with ```.where()```

In [ ]:
t6 = t5.where(mask==False, torch.tensor([0.0]))
print(t6)

tensor([[[[0.0000, 0.0000, 1.5356, 0.0000],
          [0.3892, 0.0000, 0.0000, 0.9022],
          [0.3620, 0.0000, 0.0507, 0.0000],
          [0.0000, 0.0512, 0.8866, 2.1632]],

         [[0.0000, 0.0000, 1.2385, 2.8678],
          [0.0000, 0.0000, 0.6458, 0.0000],
          [0.0000, 0.2533, 0.0000, 0.0000],
          [1.0345, 0.5941, 0.0000, 0.0000]],

         [[1.9300, 1.3803, 1.8367, 0.0000],
          [0.0000, 0.7930, 0.7457, 0.8375],
          [1.2043, 0.0000, 0.5469, 0.0000],
          [0.2851, 0.0000, 0.0000, 0.0000]]],


        [[[0.7711, 0.0000, 0.0000, 2.5042],
          [1.2424, 0.0000, 0.0000, 0.4099],
          [0.0000, 0.8026, 0.4255, 0.0000],
          [0.5143, 0.2421, 0.0000, 1.2130]],

         [[0.5058, 0.0000, 0.1627, 0.0000],
          [0.0000, 0.0000, 0.3841, 0.0000],
          [0.0000, 1.1392, 0.9415, 0.3601],
          [0.6677, 0.0000, 0.0291, 0.2366]],

         [[0.2782, 0.5943, 0.0000, 0.4913],
          [0.2238, 0.0000, 0.9020, 0.2646],
          [0.0000, 0

We can't have fractional RGB values

In [ ]:
fixed = (t6 / t6.max()) * 255
fixed = fixed.int()
print(fixed)

tensor([[[[  0,   0, 136,   0],
          [ 34,   0,   0,  80],
          [ 32,   0,   4,   0],
          [  0,   4,  78, 192]],

         [[  0,   0, 110, 255],
          [  0,   0,  57,   0],
          [  0,  22,   0,   0],
          [ 91,  52,   0,   0]],

         [[171, 122, 163,   0],
          [  0,  70,  66,  74],
          [107,   0,  48,   0],
          [ 25,   0,   0,   0]]],


        [[[ 68,   0,   0, 222],
          [110,   0,   0,  36],
          [  0,  71,  37,   0],
          [ 45,  21,   0, 107]],

         [[ 44,   0,  14,   0],
          [  0,   0,  34,   0],
          [  0, 101,  83,  32],
          [ 59,   0,   2,  21]],

         [[ 24,  52,   0,  43],
          [ 19,   0,  80,  23],
          [  0,   0, 133,  16],
          [ 43,  37,   0,   4]]]], dtype=torch.int32)


We can multiply and add tensors

In [ ]:
t7 = torch.tensor([1, 2, 3, 4])
t8 = torch.tensor([5, 6, 7, 8])
added = t7 + t8
multed = t7 * t8
print(added)
print(multed)

tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])


If you have a list of tensors for whatever reason, you can "stack" them into a single batch.

In [ ]:
stacked = torch.stack([t7, t8])
print(stacked)
print(stacked.size())

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
